### ISSUE TITLE
Idle brightness cannot be changed + not applied

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP-custom-component#57]
## Version of the custom_component

0.6.0 main f597d75

## Configuration

```yaml

N/A

```

## Describe the bug
The idle brightness value can only be set during discovery and first setup of plates.

It's impossible to change this after the plate has been added to the system, if path field is empty: "User input malformed" error shows.
![kép](https://user-images.githubusercontent.com/1550668/120209417-f46cfe80-c22e-11eb-817f-6f47a2c0e3fd.png)

Also, when the plate was set during setup with a different idle brightness value, in reality it's still set to 25:
![kép](https://user-images.githubusercontent.com/1550668/120209652-38600380-c22f-11eb-9896-f2c2b45625fa.png)

## Debug log

```text

N/A

```

**Comment by nagyrobi** [comment]
Tested the fix. Introduced other problem:
The original `light.plate_3_backlight` entity will go dis-functional: _This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device._
Instead, a `light.plate_3_backlight_2` is created with the new idle brightness value. A new change of the setting will invalidate this too and then `light.plate_3_backlight_3` will be created and so on...


```
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Reloading
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Unload entry for plate plate_3
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Removing device DeviceEntry(config_entries={'18707bd25c8296a356b3667e2d4a1fb1'}, connections=set(), identifiers={('openhasp', '40f5206fe4e4')}, manufacturer='openHASP', model='Lanbon L8', name='plate_3', sw_version='0.6.0', via_device_id=None, area_id=None, name_by_user=None, entry_type=None, id='bf17711059b95b94e00238c0b1b61b40', is_new=False, disabled_by=None, suggested_area=None)
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Reloading
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Unload entry for plate plate_3
2021-06-03 14:13:06 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry plate_3 for openhasp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/openhasp/__init__.py", line 240, in async_unload_entry
    if entry.entry_id in dev.config_entries:
AttributeError: 'NoneType' object has no attribute 'config_entries'
2021-06-03 14:13:06 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry plate_3 for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 467, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-06-03 14:13:06 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry plate_3 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 79, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-06-03 14:13:06 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry plate_3 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 146, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Remove plate plate_3
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Disabling HASPObject p0b4
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Disabling HASPObject p0b5
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Setup plate_3
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Received LWT = online
2021-06-03 14:13:06 WARNING (MainThread) [custom_components.openhasp] Refreshing plate_3
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Change page 2
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] p0b4.text - Template("{{ state_attr('weather.otthondev','temperature') if not (is_state('weather.otthondev','unavailable')) }}°C") changed, updating with: 22.5°C
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] p0b5.text - Template("{{ states('sensor.time') }}") changed, updating with: 12:13
2021-06-03 14:13:06 DEBUG (MainThread) [custom_components.openhasp] Page changed to 2
2021-06-03 14:13:07 DEBUG (MainThread) [custom_components.openhasp.light] received moodlight plate_3 moodlight: {'state': False, 'brightness': 255, 'color': '#000000', 'r': 0, 'g': 0, 'b': 0}
2021-06-03 14:13:07 DEBUG (MainThread) [custom_components.openhasp.light] received light plate_3 light 12:  {'state': False}
2021-06-03 14:13:07 DEBUG (MainThread) [custom_components.openhasp.light] received light plate_3 light 14:  {'state': False}
2021-06-03 14:13:07 DEBUG (MainThread) [custom_components.openhasp.light] received light plate_3 light 27:  {'state': False}
2021-06-03 14:13:07 DEBUG (MainThread) [custom_components.openhasp.light] received backlight plate_3 backlight: {'state': True, 'brightness': 99}
```

**Comment by dgomes** [comment]
This looks unrelated (although possibly hidden until this last fix)

**Comment by dgomes** [comment]
Can't reproduce :(

**Comment by nagyrobi** [comment]
Seems fixed, however the entity (friendly) names are deleted after configuration.

**Comment by nagyrobi** [comment]
The name deletion is confirmed on 2 different systems.

**Comment by dgomes** [comment]
please open a new issue, your description seams unrelated (and this issue is already 2 different issues)
